version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.5.1-node-browsers
         environment:
           MYSQL_USER: user
           RAILS_ENV: test
           RAKE_ENV: test
       - image: circleci/mysql:latest
         environment:
           MYSQL_ROOT_PASSWORD: rootpw
           MYSQL_DATABASE: social_service_test
           MYSQL_USER: user
           MYSQL_PASSWORD: passw0rd

     steps:
       - checkout

       # Download and cache dependencies
       - restore_cache:
           keys:
             - v1-dependencies-{{ checksum "Gemfile.lock" }}
             # fallback to using the latest cache if no exact match is found
             - v1-dependencies-

       - run:
           name: Configure Bundler
           command: |
             echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
             source $BASH_ENV
             gem install bundler -v 2.0.1
       - run:
           name: install dependencies
           command: |
             bundle install --jobs=4 --retry=3 --no-deployment --path vendor/bundle
       - save_cache:
           paths:
             - ./vendor/bundle
           key: v1-dependencies-{{ checksum "Gemfile.lock" }}

       # Database setup
       - run:
           name: Wait for DB
           command: dockerize -wait tcp://localhost:5432 -timeout 1m

       - run: bundle exec rake db:create
       - run: bundle exec rake db:schema:load

       # run lints
       - run:
           name: run rubocop
           command: bundle exec rubocop

       # run tests!
       - run:
           name: run tests
           command: bundle exec rails test

       # run tests!
       - run:
           name: run system test
           command: bundle exec rails test:system
